export const types = {
  AUTH_ERROR: 'AUTH_ERROR',
  CLEAR_AUTH_ERROR: 'CLEAR_AUTH_ERROR',
  AFTER_EMAIL_RECOVERY: 'AFTER_EMAIL_RECOVERY',
  ADD_USER: 'ADD_USER',
  EDIT_USER: 'EDIT_USER',
  LOGGED_IN: 'LOGGED_IN',
  SAVE_USER_DATA: 'SAVE_USER_DATA',
  CLEAR_SEARCH_CAMPAIGNS: 'CLEAR_SEARCH_CAMPAIGNS',
  ADD_SEARCH_CAMPAIGN: 'ADD_SEARCH_CAMPAIGN',
  ADD_CURRENT_ACTIONS: 'ADD_CURRENT_ACTIONS',
  CLEAR_CURRENT_ACTIONS: 'CLEAR_CURRENT_ACTIONS',
  CURRENT_CAMPAIGN: 'CURRENT_CAMPAIGN',
  CURRENT_ACTION: 'CURRENT_ACTION',
  VERIFY_EMAIL: 'VERIFY_EMAIL'
}
